name: quickstart-test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review, labeled, unlabeled, reopened ]
  workflow_dispatch:

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lra-test:
    name: quickstart test with JDK ${{ matrix.java-version }}
    timeout-minutes: 120
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        
      - name: Check for `skip-tests` label
        id: check-label
        run: |
          echo "should_skip=false" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Checking labels on PR #${{ github.event.pull_request.number }}..."
            if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-tests') }}" == "true" ]]; then
              echo "Label 'skip-tests' found. Skipping job."
              echo "should_skip=true" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set up JDK ${{ matrix.java-version }}
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/org/jboss
            !~/.m2/repository/org/wildfly
          key: maven-${{ runner.os }}-core
          restore-keys: |
            maven-${{ runner.os }}-

      - name: quickstart test
        if: steps.check-label.outputs.should_skip != 'true'
        run: |
          git config --global user.email "lra@jbosstm.com"
          git config --global user.name "lra-bot"
          WORKSPACE=$PWD ./scripts/hudson/quickstart.sh
        env:
          PULL_DESCRIPTION_BODY: ${{ github.event.pull_request.body }}

      - uses: actions/upload-artifact@v6
        if: steps.check-label.outputs.should_skip != 'true' && always()
        with:
          name: lra-logs-jdk${{ matrix.java-version }}
          path: |
            jboss-as/dist/target/wildfly-*/standalone/log/
            **/ObjectStore*/**
            **/tx-object-store/**
            **/*tx-object-store.zip
            **/target/*surefire-reports*/**
            **/target/*failsafe-reports*/**
          if-no-files-found: error
